FROM node:alpine AS compile-image
WORKDIR /app
COPY ./package.json /app/
RUN npm i npm@latest -g
RUN npm install -g @angular/cli 
RUN npm install

FROM compile-image as final
COPY ./ /app
RUN ng build --prod

# Estagio 2 - Será responsavel por expor a aplicação
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=final /app/dist/ItubExchange /usr/share/nginx/html

EXPOSE 4200 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]