FROM node:alpine AS compile-image

WORKDIR /app
COPY ./ /app/
RUN npm i npm@latest -g
RUN npm install
ARG env=prod
RUN npm run build

# Estagio 2 - Será responsavel por expor a aplicação
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=compile-image /app/dist/ItubExchange /usr/share/nginx/html

EXPOSE 4200 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]